/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as CardsImport } from './routes/cards'
import { Route as IndexImport } from './routes/index'
import { Route as CardsIdImport } from './routes/cards_.$id'

// Create/Update Routes

const CardsRoute = CardsImport.update({
  path: '/cards',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const CardsIdRoute = CardsIdImport.update({
  path: '/cards/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/cards': {
      id: '/cards'
      path: '/cards'
      fullPath: '/cards'
      preLoaderRoute: typeof CardsImport
      parentRoute: typeof rootRoute
    }
    '/cards/$id': {
      id: '/cards/$id'
      path: '/cards/$id'
      fullPath: '/cards/$id'
      preLoaderRoute: typeof CardsIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  CardsRoute,
  CardsIdRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/cards",
        "/cards/$id"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/cards": {
      "filePath": "cards.tsx"
    },
    "/cards/$id": {
      "filePath": "cards_.$id.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
